### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by syptic** [Vulxn/cse-15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [ ] All titles of sections are formatted as headers or similar
  - 2nd subtitle has H2 in it.
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Missing links(such as vscode download page), code blocks(ssh command, cp or even some screenshots could all be in code blocks), titles for different sections/steps of the tutorial, an example in optimization with key stroke count and possible optimization techniques. 

Edit:
Complete the last example and edit the 2nd subtitle.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page
```

**Comment by Vulxn** [comment]
Fixed my lord, anything else?
